---
kind: pipeline
name: release

steps:
  - name: build & push release image
    image: thegeeklab/drone-docker-buildx:20.11@sha256:6edea41f1fdf2b3c0a536ce3f14da05ee261205919dfbdee6df58a050f2474a7
    settings:
      auto_tag: true
      repo: mazzolino/librespot-snapserver
      platforms:
        - linux/amd64
        - linux/arm64
        - linux/armhf
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
---
kind: signature
hmac: 845b542a245bd615a92889da99ea145a2fdbc0357e4d825198519bb802eb63b1

...
