---
kind: pipeline
name: release

steps:
  - name: build & push release image
    image: thegeeklab/drone-docker-buildx:20.12.1@sha256:5439d579562a605953b386df64f1a469720f5358fa1bd0bdf225ae8d48d652b7
    settings:
      auto_tag: true
      repo: mazzolino/librespot-snapserver
      cache_from: mazzolino/librespot-snapserver:cache
      cache_to: mazzolino/librespot-snapserver:cache
      platforms:
        - linux/amd64
        - linux/arm64
        - linux/armhf
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
---
kind: signature
hmac: 2882621298eb9832e2ff71d050d3b39c6d4f8864600df0aa29107ce4617ad0ea

...
