version: "3.3"

services:
  app:
    build:
      context: .
      args:
        - ARCH
        - SNAPCAST_VERSION
    image: mazzolino/librespot-snapserver:${SNAPCAST_VERSION}-${ARCH}
    networks:
      - host

networks:
  host:
    external:
      name: host
